version: '3'

tasks:
  mobile:
    dir: ./mobile
    cmds:
      - ebitenmobile bind -target ios -o Secrets.xcframework .

  mobile-deploy:
    deps:
      - mobile
    dir: ./mobile/Secrets
    cmds:
      - xcodebuild -scheme Secrets -configuration Debug -sdk iphoneos -derivedDataPath build 
      - ios-deploy --bundle build/Build/Products/Debug-iphoneos/Secrets.app --nostart --no-wifi 
